package cli

import _ "embed"

// oauthSuccessPageHTML is generated by agora-cli-login-redirect and committed
// so normal CLI builds never require Node.js, pnpm, or network access.
//
//go:embed oauthui/oauth-success.html
var oauthSuccessPageHTML string

//go:embed oauthui/oauth-success-cn.html
var oauthSuccessPageCNHTML string
