package cli

import (
	"strings"
	"testing"
)

func TestEmbeddedOAuthSuccessPageIsSelfContained(t *testing.T) {
	for name, html := range map[string]string{
		"global": oauthSuccessPageHTML,
		"cn":     oauthSuccessPageCNHTML,
	} {
		if html == "" {
			t.Fatalf("embedded %s OAuth success page is empty", name)
		}
		if !strings.Contains(html, "Code generated by agora-cli-login-redirect") {
			t.Fatalf("embedded %s page is missing its generated-file notice", name)
		}
		for _, forbidden := range []string{"<script", "http://", "https://", "/_next/"} {
			if strings.Contains(html, forbidden) {
				t.Fatalf("embedded %s page contains forbidden runtime dependency %q", name, forbidden)
			}
		}
	}
}

func TestOAuthCallbackSuccessPageUsesFinalGlobalDesign(t *testing.T) {
	html := renderOAuthCallbackSuccessPage(callbackPageConfig{Region: regionGlobal}, oauthSuccessPageData{
		AuthenticatedAt: "2026-07-22 14:30 UTC",
		ExpiresAt:       "2026-07-22 16:30 UTC",
		CLIVersion:      "v0.2.2",
	})

	for _, want := range []string{
		`<html lang="en"`,
		"Authentication successful",
		"agora auth status",
		"✓ ready",
		"2026-07-22 14:30 UTC",
		"2026-07-22 16:30 UTC",
		"v0.2.2",
		"You can safely close this window and return to your terminal.",
	} {
		if !strings.Contains(html, want) {
			t.Fatalf("expected global login page to contain %q", want)
		}
	}

	for _, forbidden := range []string{"<script", "https://", "/_next/", "dev@agora.sh", "cli:full-access", "shengwang", "声网", "brand-logo-cn"} {
		if strings.Contains(html, forbidden) {
			t.Fatalf("global login page should not contain legacy variant content %q", forbidden)
		}
	}
}

func TestOAuthCallbackSuccessPageDefaultsToGlobalBranding(t *testing.T) {
	html := renderOAuthCallbackSuccessPage(callbackPageConfig{Region: "test"}, oauthSuccessPageData{})

	for _, want := range []string{
		"Authentication successful",
		"agora auth status",
		"✓ ready",
	} {
		if !strings.Contains(html, want) {
			t.Fatalf("expected fallback login page to contain %q", want)
		}
	}

	for _, forbidden := range []string{"shengwang", "声网", "brand-logo-cn"} {
		if strings.Contains(html, forbidden) {
			t.Fatalf("fallback login page should not contain China branding %q", forbidden)
		}
	}
}

func TestOAuthCallbackSuccessPageUsesFinalChinaDesign(t *testing.T) {
	html := renderOAuthCallbackSuccessPage(callbackPageConfig{Region: regionCN}, oauthSuccessPageData{
		AuthenticatedAt: "2026-07-22 14:30 UTC",
		ExpiresAt:       "2026-07-22 16:30 UTC",
		CLIVersion:      "v0.2.2",
	})

	for _, want := range []string{
		`<html lang="zh-CN"`,
		`aria-label="声网"`,
		"认证成功",
		"你已成功登录声网。请返回终端继续操作。",
		"agora auth status",
		"✓ 已就绪",
		"v0.2.2",
		"你可以安全地关闭此窗口并返回终端。",
	} {
		if !strings.Contains(html, want) {
			t.Fatalf("expected China login page to contain %q", want)
		}
	}

	for _, forbidden := range []string{"<script", "https://", "/_next/", "Authentication successful", "dev@agora.sh", "cli:full-access"} {
		if strings.Contains(html, forbidden) {
			t.Fatalf("China login page should not contain legacy variant content %q", forbidden)
		}
	}
}

func TestOAuthCallbackSuccessPageEscapesRuntimeValues(t *testing.T) {
	html := renderOAuthCallbackSuccessPage(callbackPageConfig{Region: regionGlobal}, oauthSuccessPageData{
		AuthenticatedAt: `<img src=x onerror=alert(1)>`,
		ExpiresAt:       `2026-07-22 16:30 UTC`,
		CLIVersion:      `<b>dev</b>`,
	})

	for _, forbidden := range []string{"<script>alert", "<img src=x", "<b>dev</b>"} {
		if strings.Contains(html, forbidden) {
			t.Fatalf("runtime page value was not escaped: %q", forbidden)
		}
	}
}

func TestOAuthCallbackErrorPageKeepsRegionBranding(t *testing.T) {
	html := renderOAuthCallbackErrorPage(callbackPageConfig{Region: regionCN}, "Login state mismatch", "Return to the terminal and restart login.")

	for _, want := range []string{
		"shengwang-page is-error",
		"Login state mismatch",
		"Return to the terminal and restart login.",
	} {
		if !strings.Contains(html, want) {
			t.Fatalf("expected error login page to contain %q", want)
		}
	}

	if strings.Contains(html, "agora auth status") {
		t.Fatal("error login page should not show success action command")
	}
}
